# Generated by Django 3.2.18 on 2023-04-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everydayblog', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
