# Generated by Django 3.2.18 on 2023-04-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everydayblog', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(0, 'BOL'), (1, 'EDC'), (2, 'Outher')], default=2, max_length=50),
        ),
    ]
