# Generated by Django 3.2.18 on 2023-04-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everydayblog', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
